42 refactor enroll
godmmt/MERN-app pull request #53
Opened 2023-08-15 14:19 UTC by godmmt

2023-08-20 10:36 UTC, godmmt commented
目前遇到待解決的問題
1. 同個課程可以被同個使用者Eroll兩次以上（這不合理）
2. 課程要放照片所以要改courseSchema
3. 課程照片要放到第三方網站（imgur）用他給的url

2023-08-24 10:14 UTC, Alanwei0502 requested changes

2023-08-24 10:14 UTC, Alanwei0502 commented on client/src/components/Enroll/index.jsx
> +          {!course.students.some((item) => item === currentUser.user._id) && (
這裡可以用ternary operator(三元運算子)

2023-08-24 10:14 UTC, Alanwei0502 commented on client/src/pages/AllCourses/index.jsx
> +        .then((data) => {
參數改名為 res

2023-08-24 10:14 UTC, Alanwei0502 commented on client/src/pages/AllCourses/index.jsx
> +            searchResult.map((course) => {
大括號和return可省略

2023-08-24 15:00 UTC, godmmt commented on client/src/components/Enroll/index.jsx
> +          {!course.students.some((item) => item === currentUser.user._id) && (
已修改為:

```
          {course.students.some((item) => item === currentUser.user._id) ? (
            <div>
              <h6>You already own this course. Click the CHECK button to view it.</h6>
              <Button onClick={handleToMyCourses}>CHECK</Button>
            </div>
          ) : (
            <Button cx='enroll-btn' onClick={handleEnroll}>
              Enroll
            </Button>
          )}
```

2023-08-24 15:30 UTC, Alanwei0502 approved these changes

2023-08-24 15:30 UTC, merged